name       : font-ubuntu-ttf
version    : 0.83
release    : 2
source     :
    - http://font.ubuntu.com/download/ubuntu-font-family-0.83.zip : 456d7d42797febd0d7d4cf1b782a2e03680bb4a5ee43cc9d06bda172bac05b42
license    : Ubuntu Font License-1.0
component  : desktop.font
summary    : Ubuntu font family
description: |
    Ubuntu font family
install    : |
      fontDir=$installdir/usr/share/fonts/truetype/ubuntu
      install -dm755 $fontDir
      mv $workdir/*.ttf $fontDir/
